@echo off
echo Setting up Python environment with uv...
uv venv
echo Activating virtual environment...
call .venv\Scripts\activate
echo Installing dependencies...
uv pip install -r requirements.txt


echo Starting FastAPI Server...
uvicorn main:app --host 127.0.0.1 --port 8000 --reload
